---
- name: Install requirements with apt
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    "{{packages | default([])}}"
  when: ansible_os_family == "Debian"
  become: yes
  tags: reqs
- name: Install requirements with dnf
  dnf: name={{item}} state=latest
  with_items:
    "{{packages | default([])}}"
  when: ansible_distribution == "Fedora"
  become: yes
  tags: reqs
- name: Install apt specific requirements
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    "{{apt_packages | default([])}}"
  when: ansible_os_family == "Debian"
  become: yes
  tags: reqs
- name: Install dnf specific requirements
  dnf: name={{item}} state=latest
  with_items:
    "{{dnf_packages | default([])}}"
  when: ansible_distribution == "Fedora"
  become: yes
  tags: reqs
- name: Install portage specific requirements
  portage: name={{item}} state=present
  with_items:
    "{{portage_packages | default([])}}"
  when: ansible_distribution == "Gentoo"
  become: yes
  tags: reqs
