---
- hosts: all
  name: Download executable and link

  vars:
    path: '{{ user_bin }}/{{ executable }}'

  tasks:
    - name: Download from url
      get_url:
        url: '{{ url }}'
        dest: '{{ path }}'
        force: yes

    - name: Make file executable
      file:
        path: '{{ path }}'
        mode: 0744
...
