---
- hosts: all
  name: Download executable

  vars:
    path:
      "{{ user_bin }}/{{ exec }}"

  tasks:
    - name: Download from {{ url }}
      get_url:
        url:
          "{{ url }}"
        dest:
          "{{ path }}"

    - name: Make {{ exec }} executable
      file:
        path:
          "{{ path }}"
        mode:
          0744
