---
- hosts: all
  name: Add authorized ssh key

  tasks:
    - name: Add authorized ssh key
      authorized_key: user={{ local_user }}
                      key={{ lookup('file', ssh_public_key) }}
      become:
        "{{ _remote_user is defined and _remote_user != 'root' }}"
      tags: ssh-key
