---
- include: install-doctl.yaml
  tags: doctl

- hosts: all

  vars_files:
    - vars/user_vars.yaml
    - vars/paths.yaml

  vars:
    key_name:
      "{{ ansible_hostname }}"
    fetch_destination:
      "/tmp/{{ ansible_hostname }}-public-key"

  tasks:
    - fetch:
        src:
          "{{ remote_user_ssh_public_key }}"
        dest:
          "{{ fetch_destination }}"
        flat: yes
      tags: fetch-pubkey

    - name: Import public key to Digital Ocean
      local_action:
        command doctl compute ssh-key import {{ ansible_hostname }} --public-key-file {{ remote_user_ssh_public_key }}
