- hosts: all
  name: Add SSH key to Gitlab

  vars_files:
    - vaults/gitlab_vars.yaml

  vars:
    deps:
      common:
        [curl]

  roles:
    - packages

  post_tasks:
    - name: Read SSH key
      command: cat {{ user_home }}/.ssh/id_rsa.pub
      register: ssh_pubkey
      tags: key-read

    - name: Add key to Gitlab
      command:
        # Can't seem to able to this with the uri module
        curl https://gitlab.com/api/v3/user/keys -F 'title={{ ansible_user_id }}@{{ ansible_hostname }}'
            -F 'key={{ ssh_pubkey.stdout }}' -F 'private_token={{ gitlab_access_token }}'
      tags: key-add
