---
- hosts: all
  name: Add authorized ssh key

  vars_files:
    - vars/user_vars.yaml

  vars:
    username: "{{ local_user }}"

  tasks:
    - name: Add authorized ssh key
      authorized_key: user={{ username }}
                      key={{ lookup('file', ssh_public_key) }}
      tags: ssh-key
