---
- hosts: all
  name: Add SSH key to Gitlab

  vars_files:
    - vaults/gitlab_vars.yaml

  vars:
    public_key: '{{ user_home }}/.ssh/id_rsa.pub'
    key_name: '{{ ansible_user_id }}@{{ ansible_hostname }}'
    key: '{{ lookup("file", "{{ public_key }}") }}'
    access_token: '{{ lookup("passwordstore", "{{ gitlab_access_token_secret }}") }}'
    endpoint: https://gitlab.com/api/v4/user/keys

  tasks:
    - debug:
        var: access_token

    - name: Add key to Gitlab
      uri:
        url: '{{ endpoint }}'
        body:
          title: '{{ key_name }}'
          key: '{{ key }}'
          private_token: '{{ access_token }}'
        body_format: form-urlencoded
        method: POST
        status_code: 201
...
