---
- hosts: all
  name: Add SSH key to GitHub

  vars_files:
    - vars/paths.yaml

  vars_prompt:
    - name: access_token
      prompt: "GitHub access token?"

  tasks:
    - name: Read SSH key
      command: cat {{ user_home }}/.ssh/id_rsa.pub
      register: ssh_pubkey

    - name: Add key to GitHub
      github_key:
        name:
          "{{ ansible_hostname }}"
        state:
          present
        pubkey:
          "{{ ssh_pubkey.stdout }}"
        token:
          "{{ access_token }}"
