---
- hosts: all
  name: Add authorized ssh key
  remote_user:
      "{{ user | default('root') }}"

  tasks:
    - name: Add authorized ssh key
      authorized_key: user={{ local_user }}
                      key={{ lookup('file', ssh_public_key) }}
      become:
        "{{ user is defined and user != 'root' }}"
      tags: ssh-key
