---
- hosts: all
  name: Add SSH key to GitHub

  vars_files:
    - vaults/github_vars.yaml

  tasks:
    - name: Read SSH key
      command: cat {{ user_home }}/.ssh/id_rsa.pub
      register: ssh_pubkey

    - name: Add key to GitHub
      github_key:
        name:
          "{{ ansible_hostname }}"
        state:
          present
        pubkey:
          "{{ ssh_pubkey.stdout }}"
        token:
          "{{ github_access_token }}"
