---
- hosts: all
  name: Clone host specific dotfiles

  vars_files:
    - vars/paths.yaml

  vars:
    homeshick:
      repos:
        - "{{ ansible_hostname }}"
        - cache
      clone_type:
        ssh

  roles:
    - homeshick
