---
- hosts: all
  name: Clone dotfiles

  vars:
    homeshick:
      repos:
        - host:
            gitlab
          castle:
            base
        - host:
            gitlab
          castle:
            basic
        - host:
            github
          castle:
            homebin

  roles:
    - homeshick
