---
- hosts: all
  name: Clone host specific dotfiles

  vars:
    homeshick:
      repos:
        - host: gitlab
          castle: "{{ ansible_hostname }}"
        - host: gitlab
          castle: cache
      clone_type:
        ssh

  roles:
    - homeshick
