---
- hosts: all
  name: Clone dotfiles

  vars_files:
    - vars/paths.yaml

  vars:
    homeshick:
      repos:
        - base
        - basic
        - homebin
    homeshick_init:
      yes

  roles:
    - homeshick
