---
- hosts: all
  name: Clone dotfiles

  vars_files:
    - vars/paths.yaml
    - homesick_vars.yaml

  vars:
    deps:
      pkg:
        bash
    bash_executable:
      /bin/bash

  pre_tasks:
    - name: Set bash executable
      set_fact:
        bash_executable: /usr/local/bin/bash
      when: ansible_distribution == "FreeBSD"
      tags: link

    - name: Mount fdescfs
      mount:
        name: /dev/fd
        src: fdesc
        fstype: fdescfs
        state: present
      become: yes
      when: ansible_distribution == "FreeBSD"
      tags: link

  tasks:

    - name: Clone homesick repos
      git: repo={{ gitlab_base_url }}/{{ gitlab_username }}/{{ item }}.git
           dest={{ homesick_repos_path }}/{{ item }}
           accept_hostkey=true
      with_items:
        "{{ homesick_repos }}"
      tags: clone

    - name: Link homesick repos
      shell: |
        source $HOME/.homesick/repos/homeshick/homeshick.sh
        homeshick link -f {{ item }}
      args:
        executable: "{{ bash_executable }}"
      with_items:
        "{{ homesick_repos }}"
      tags: link

  roles:
    - packages
