---
- hosts:
    all
  name:
    Configure Synaptics Touchpad

  vars:
    apt:
      - xserver-xorg-input-synaptics
    dnf_yum:
      - xorg-x11-drv-libinput

  roles:
    - packages

  post_tasks:
    - name:
        Create Xorg configuration directory
      file:
        path:
          /etc/X11/xorg.conf.d
        state:
          directory
      become:
        true

    # https://wiki.archlinux.org/index.php/Touchpad_Synaptics#Configuration
    - name:
        Enable tapping for buttons 1, 2, 3 and edge scrolls
      blockinfile:
        path:
          /etc/X11/xorg.conf.d/70-synaptics.conf
        create:
          yes
        block: |
          Section "InputClass"
              Identifier "touchpad"
              Driver "synaptics"
              MatchIsTouchpad "on"
                  Option "TapButton1" "1"
                  Option "TapButton2" "2"
                  Option "TapButton3" "3"
                  Option "VertEdgeScroll" "on"
                  Option "HorizEdgeScroll" "on"
          EndSection
      become:
        true
