---
- hosts:
    all
  name:
    Configure Synaptics Touchpad

  vars:
    apt:
      - xserver-xorg-input-libinput
    dnf_yum:
      - xorg-x11-drv-libinput

  roles:
    - packages

  post_tasks:
    - name:
        Create Xorg configuration directory
      file:
        path:
          /etc/X11/xorg.conf.d
        state:
          directory
      become:
        true

    # https://wiki.archlinux.org/index.php/Libinput#Common_options
    - name:
        Enable tapping and edge scrolls
      blockinfile:
        path:
          /etc/X11/xorg.conf.d/30-touchpad.conf
        create:
          yes
        block: |
          Section "InputClass"
              Identifier "touchpad"
              Driver "synaptics"
              MatchIsTouchpad "on"
              Option "Tapping" "on"
              Option "ScrollMethod" "twofinger"
              Option "ScrollMethod" "edge"
          EndSection
      become:
        true
