---
- import_playbook: _download_executable.yaml
  vars:
    version: 1.6.3/2.12-1.6.3
    executable: ammonite
    url: https://github.com/lihaoyi/Ammonite/releases/download/{{ version }}

- hosts: all
  name: Add shebang to Ammonite script

  tasks:
    - name: Add shebang to script
      lineinfile:
        line: '#!/usr/bin/env sh'
        insertbefore: BOF
        path: '{{ user_bin }}/ammonite'
...
