- hosts: all
  name: Download and link Terraform

  vars:
    version:
      0.11.11
    download_and_link:
      url: https://releases.hashicorp.com/terraform/{{ version }}/terraform_{{ version }}_linux_amd64.zip
      exec_only: yes

  roles:
    - download-and-link
