---
- hosts: all
  name: DnL cutting-edge Thunderbird

  vars:
    version: 60.0
    language: en-GB
    download_and_link:
      url: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/{{ version }}/linux-x86_64/{{ language }}/thunderbird-{{ version }}.tar.bz2
      link:
        - src: thunderbird

  roles:
    - download-and-link
