---
- hosts: all
  name: Download and link jshell

  vars_files:
    - vars/paths.yaml

  vars:
    release:
      url:
        http://download.java.net/java/jdk9/archive/166/binaries/jdk-9-ea+166_linux-x64_bin.tar.gz
      name:
        jshell

    util:
      link:
        - bin/jshell

  roles:
    - download
    - util
