---
- hosts: all
  name: Export secret key

  vars_files:
    - gpg_vars.yaml

  tasks:
    - name: Ensure that the local copy directory exists
      local_action: file path={{local_gpg_key_location | dirname}} state=directory
      tags: export

    - name: Export gpg key
      local_action: command gpg2 --output {{ local_gpg_key_location }} --armor --export-secret-keys {{gpg_id}}
      tags: export

    - name: Ensure that the copy directory exists
      file: path={{remote_gpg_key_location | dirname}} state=directory
      tags: export

    - name: Copy the GPG private key to remote machine
      copy:
        src: "{{ local_gpg_key_location }}"
        dest: "{{ remote_gpg_key_location }}"
      tags: export

    - name: Import secret key
      shell: |
        gpg2 --import {{remote_gpg_key_location}}
      tags: init

    - name: Cleanup local export
      local_action: command shred {{local_gpg_key_location}}
      tags: cleanup

    - name: Cleanup local directory
      local_action: file path={{local_gpg_key_location | dirname}} state=absent
      tags: cleanup

    - name: Cleanup remote
      shell: |
        shred {{remote_gpg_key_location}}
        rm -r {{remote_gpg_key_location | dirname}}
      tags: cleanup
...
