---
- hosts: all
  name: Initialize Password Store

  vars_files:
    - gpg_vars.yaml

  tasks:
    - name: Ensure that the local copy directory exists
      file:
        path: '{{local_gpg_key_location | dirname}}'
        state: directory
      delegate_to: localhost
      tags: export

    - name: Export gpg key
      command: gpg --output {{ local_gpg_key_location }} --armor --export-secret-keys {{gpg_id}}
      delegate_to: localhost
      tags: export

    - name: Ensure that the copy directory exists
      file:
        path: '{{remote_gpg_key_location | dirname}}'
        state: directory
      tags: export

    - name: Copy the GPG private key to remote machine
      copy:
        src: '{{ local_gpg_key_location }}'
        dest: '{{ remote_gpg_key_location }}'
      tags: export

    - name: Initialize pass
      shell: |
        gpg --import {{remote_gpg_key_location}}
        pass init {{gpg_id}}
      tags: init

    - name: Cleanup local export
      command: shred -u {{local_gpg_key_location}}
      delegate_to: localhost
      tags: cleanup

    - name: Cleanup local directory
      file:
        path: '{{local_gpg_key_location | dirname}}'
        state: absent
      delegate_to: localhost
      tags: cleanup

    - name: Cleanup remote
      shell: |
        shred -u {{remote_gpg_key_location}}
        rm -r {{remote_gpg_key_location | dirname}}
      tags: cleanup
...
