---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    dactyl_path: "{{repo_clone_path}}/dactyl"
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - firefox
        - zip
      when: ansible_os_family == "Debian"
    - dnf: name={{item}} state=latest
      become: yes
      with_items:
        - firefox
        - zip
      when: ansible_distribution == "Fedora"
  tasks:
    - name: Clone dactyl
      git: repo=https://github.com/5digits/dactyl dest={{dactyl_path}}
      tags: clone
    - name: Install pentadactyl
      shell: |
        DISPLAY=:0 make installxpi
      args:
        chdir: "{{dactyl_path}}/pentadactyl"
      tags: install
