---
- hosts: all
  name: Initialize directories

  vars_files:
    - vars/paths.yaml

  tasks:
    - name: Initialize path
      file:
        path:
          "{{ item }}"
        state:
          directory
      with_items:
        - "{{ download_path }}"
        - "{{ user_home }}/.vim/swap"
        - "{{ user_bin }}"
