---
- name: Initialise Salt
  hosts: all

  vars:
    sudo_file: /etc/sudoers.d/{{ ansible_user_id }}-nopasswd

    deps:
      common:
        - git
      apt:
        - openssh-server
        - python3-dev
        - virtualenv
      dnf_yum:
        - gcc
        - openssh-server
        - python3-devel
        - python3-virtualenv
      pacman:
        - openssh

  roles:
    - packages

  post_tasks:
    - name: Install Salt with pip
      pip:
        name: salt==2019.2.2
        virtualenv: '{{ virtualenv_base }}/salt'

    - name: Enable OpenSSH service
      systemd:
        name: sshd
        state: started
        enabled: true
      become: yes

    - name: Clone Salt states repository
      git:
        repo: https://github.com/femnad/anr.git
        dest: '{{ personal_repos_dir }}/anr'

    - name: Ensure .ssh directory
      file:
        path: '{{ user_home }}/.ssh'
        state: directory

    - name: Check if there is an SSH key
      stat:
        path: '{{ user_home }}/.ssh/id_rsa'
      register: ssh_key

    - name: Add non passphrased SSH key
      openssh_keypair:
        path: '{{ user_home }}/.ssh/id_rsa'
      when: not ssh_key.stat.exists

    - name: Add own key as authorized
      authorized_key:
        user: '{{ ansible_user }}'
        key: "{{ lookup('file', user_home + '/.ssh/id_rsa.pub') }}"

    - name: Add localhost as known host
      shell: ssh-keyscan localhost > {{ user_home }}/.ssh/known_hosts

    - name: Enable passwordless sudo
      lineinfile:
        create: yes
        dest: '{{ sudo_file }}'
        line: '{{ ansible_user_id }} ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
      become: yes
...
