---
- name: Initialise Salt
  hosts: all

  tasks:
    - name: Add Salt repository key
      apt_key:
        url: https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest/SALTSTACK-GPG-KEY.pub
      when: ansible_distribution == 'Ubuntu'
      become: yes

    - name: Add Salt repository
      apt_repository:
        repo: deb [arch=amd64] http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic main
      become: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install Salt components
      package:
        name: salt-{{ item }}
      loop:
        - common
        - master
        - minion
        - ssh
      become: yes
      when: (ansible_distribution == 'Fedora' and ansible_distribution_major_version == '30') or ansible_distribution == 'Ubuntu'

    - name: Install Python 3 development package
      package:
        name: python3-devel
      become: yes
      when: ansible_distribution == 'Fedora' and ansible_distribution_major_version == '30'

    - name: Install Salt with pip
      pip:
        name: salt==2019.2.2
        virtualenv: '{{ virtualenv_base }}/salt'
      when: ansible_distribution == 'Fedora' and ansible_distribution_major_version == '31'

    - name: Exclude Salt packages from upgrades
      lineinfile:
        path: /etc/dnf/dnf.conf
        line: excludepkgs = salt, salt-api, salt-cloud, salt-master, salt-minion, salt-ssh, salt-syndic
      become: yes
      when: ansible_distribution == 'Fedora' and ansible_distribution_major_version == '31'

    - name: Install Salt
      package:
        name: salt
      become: yes
      when: ansible_distribution == 'Archlinux'

    - name: Install OpenSSH server and git
      package:
        name:
          - git
          - openssh-server
      when: ansible_distribution != 'Archlinux'
      become: yes

    - name: Install OpenSSH server and git
      package:
        name:
          - git
          - openssh
      when: ansible_distribution == 'Archlinux'
      become: yes

    - name: Enable OpenSSH service
      systemd:
        name: sshd
        state: started
        enabled: true
      become: yes

    - name: Clone Salt states repository
      git:
        repo: https://github.com/femnad/anr.git
        dest: '{{ personal_repos_dir }}/anr'

    - name: Ensure .ssh directory
      file:
        path: '{{ user_home }}/.ssh'
        state: directory

    - name: Add non passphrased SSH key
      openssh_keypair:
        path: '{{ user_home }}/.ssh/id_rsa'

    - name: Add own key as authorized
      authorized_key:
        user: '{{ ansible_user }}'
        key: "{{ lookup('file', user_home + '/.ssh/id_rsa.pub') }}"

    - name: Add localhost as known host
      shell: ssh-keyscan localhost > {{ user_home }}/.ssh/known_hosts
...
