---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - scripts_dir: "{{user_home}}/z/ce"
  pre_tasks:
    - apt: name={{item}} state=latest update_cache=yes
      when: ansible_os_family == "Debian"
      with_items:
        - openvpn
        - unzip
      become: yes
    - dnf: name={{item}} state=latest
      with_items:
        - openvpn
        - unzip
      become: yes
      when: ansible_distribution == "Fedora"
    - name: Install requirements with portage
      portage: name=openvpn state=present
      become: yes
      tags: install-reqs
      when: ansible_distribution == "Gentoo"
  tasks:
    - name: Generate OpenVPN scripts
      script: init-pia-scripts.sh {{scripts_dir}}
      tags: genscripts
