---
- import_playbook: install-x.yaml
  tags: xorg

- import_playbook: install-dzen.yaml
  tags: dzen

- hosts: all
  name: Initialize Xorg

  vars:
    deps:
      apt:
        libnotify-bin

  roles:
    - packages

- import_playbook: install-over-here.yaml
  tags: non-conformist-wm

- import_playbook: cnl-notify-recv.yaml
  tags: non-conformist-wm
