---
- hosts: all
  name: Initialize a workstation

- include: init-ngh.yaml
  tags: ngh

- include: init-sound.yaml
  tags: sound

- include: init-x.yaml
  tags: xorg

- include: install-laptop-tools.yaml
  tags: laptop

- include: install-ysnpassmenu.yaml
  tags: ysnpassmenu
