---
- hosts: all
  name: Initialize the ability to hears sounds

  vars:
    deps:
      apt:
        - alsa-utils
        - pulseaudio
      dnf_yum:
        - alsa-utils
        - alsa-plugins-pulseaudio
        - pulseaudio

  roles:
    - packages
