---
- hosts: all

  vars_files:
    - vars/paths.yaml
    - tarsnap_vars.yaml

  tasks:
    - name: Create key file directory
      file: name={{tarsnap_key_dir}} state=directory
    - name: Copy latest Tarsnap key file
      copy: src={{tarsnap_key_file}} dest={{tarsnap_key_file}}
