---
- hosts: all
  name: Install Python development packages

  vars:
    deps:
      apt:
        - libffi-dev
        - libssl-dev
        - libyaml-dev
        - python-dev
        - python3-dev
        - python-pip
        - python3-pip
        - python-virtualenv
        - python3-virtualenv

  roles:
    - packages

  tasks:
    - name: Install flake8
      command: pip install flake8 --user
