---
- hosts: all
  vars_files:
    - user_vars.yaml
  tasks:
    - name: Add user {{username}}
      user: name={{username}} group=users groups=sudo shell=/bin/bash
      tags: user
    - name: Add authorized ssh key
      authorized_key: user={{ username }}
                      key={{ lookup('file', ssh_public_key) }}
      tags: ssh-key
