---
- name: Initialise Salt
  hosts: all

  tasks:
    - name: Install requirements
      package:
        name:
          - git
          - openssh-server
          - python3-virtualenv
      when: ansible_distribution != 'Archlinux'
      become: yes

    - name: Install OpenSSH server and git
      package:
        name:
          - git
          - openssh
      when: ansible_distribution == 'Archlinux'
      become: yes

    - name: Install Salt with pip
      pip:
        name: salt==2019.2.2
        virtualenv: '{{ virtualenv_base }}/salt'

    - name: Enable OpenSSH service
      systemd:
        name: sshd
        state: started
        enabled: true
      become: yes

    - name: Clone Salt states repository
      git:
        repo: https://github.com/femnad/anr.git
        dest: '{{ personal_repos_dir }}/anr'

    - name: Ensure .ssh directory
      file:
        path: '{{ user_home }}/.ssh'
        state: directory

    - name: Add non passphrased SSH key
      openssh_keypair:
        path: '{{ user_home }}/.ssh/id_rsa'

    - name: Add own key as authorized
      authorized_key:
        user: '{{ ansible_user }}'
        key: "{{ lookup('file', user_home + '/.ssh/id_rsa.pub') }}"

    - name: Add localhost as known host
      shell: ssh-keyscan localhost > {{ user_home }}/.ssh/known_hosts
...
