---
- hosts: all
  name: Effect ability to listen to Spotify

  vars:
    deps:
      apt:
        - mpc
        - ncmpcpp

  roles:
    - packages

- import_playbook: init-sound.yaml
  tags: sound

- import_playbook: install-mopidy.yaml
  tags: mopidy

- import_playbook: install-abduco.yaml
  tags: abduco
