---
- hosts: all
  name: Enable contrib and non-free repos

  tasks:
    - name: Enable repos
      apt_repository:
        repo:
          "{{ item }}"
        state:
          present
      become:
        yes
      with_items:
        - deb http://ftp.de.debian.org/debian/ stretch contrib non-free
        - deb-src http://ftp.de.debian.org/debian/ stretch contrib non-free
        - deb http://security.debian.org/debian-security stretch/updates contrib non-free
        - deb-src http://security.debian.org/debian-security stretch/updates contrib non-free
        - deb http://ftp.de.debian.org/debian/ stretch-updates contrib non-free
        - deb-src http://ftp.de.debian.org/debian/ stretch-updates contrib non-free
