---
- hosts: all
  name: Initialize a workstation

- import_playbook: init-ngh.yaml
  tags: ngh

- import_playbook: add-user-to-groups.yaml
  tags: groups

- import_playbook: init-sound.yaml
  tags: sound

- import_playbook: init-x.yaml
  tags: xorg

- import_playbook: install-browsers.yaml
  tags: browser

- import_playbook: install-laptop-tools.yaml
  tags: laptop

- import_playbook: install-ysnpassmenu.yaml
  tags: ysnpassmenu

- import_playbook: enable-subpixel-rendering.yaml
  tags: fonts
