---
- hosts: all
  name: Install and initialize Firefox

  vars_files:
    - vars/paths.yaml

  vars:
    deps:
      apt:
        - firefox
      dnf_yum:
        - firefox

  roles:
    - packages


  post_tasks:
    - name: Install FireGestures
      command: firefox https://addons.mozilla.org/firefox/downloads/latest/firegestures/addon-6366-latest.xpi?src=dp-btn-primary
      tags: firegestures
      environment:
        DISPLAY:
          :0.0

    - name: Install vimperator
      command: firefox https://addons.mozilla.org/firefox/downloads/latest/vimperator/addon-4891-latest.xpi?src=dp-btn-primary
      tags: firefox
      environment:
        DISPLAY:
          :0.0
