---
- hosts: all
  name: Initialize the ability to hear sounds

  vars:
    deps:
      apt:
        - alsa-utils
        - pulseaudio
      dnf_yum:
        - alsa-utils
        - alsa-plugins-pulseaudio
        - pulseaudio
        - pulseaudio-utils

  roles:
    - packages
