---
- hosts: all
  name: Init a NGH (non-generic host)

- import_playbook: init-mwe.yaml
  tags: mwe

- import_playbook: install-tarsnap.yaml
  tags: tarsnap

- import_playbook: generate-ssh-key.yaml
  tags: ssh-key

- import_playbook: add-github-ssh-key.yaml
  tags: github

- import_playbook: add-gitlab-ssh-key.yaml
  tags: gitlab

- import_playbook: add-digital-ocean-ssh-key.yaml
  tags: digital-ocean

- import_playbook: clone-ngh-dotfiles.yaml
  tags: ngh-dotfiles
