---
- import_playbook:
    init-workstation.yaml
  tags:
    workstation

- import_playbook:
    install-ratpoison.yaml
  tags:
    ratpoison

- import_playbook:
    init-nonfree-debian-repos.yaml
  tags:
    nonfree

- import_playbook:
    set-intel-backlight.yaml
  tags:
    backlight

- import_playbook:
    cnl-notify-recv.yaml
  tags:
    notify-recv

- import_playbook:
    install-rossa.yaml
  tags:
    rossa

- hosts: all
  name: Initialize rubidium

  vars:
    deps:
      apt:
        - firmware-iwlwifi
        - firmware-linux
        - firmware-linux-free
        - firmware-linux-nonfree
        - fonts-3270
        - lxterminal
        - network-manager
        - rxvt-unicode-256color

  roles:
    - { role: packages, tags: host-specific }
