---
- name: Init sudo
  hosts: all

  tasks:
    - name: Install sudo
      package:
        name: sudo
      become: yes

    - name: Set passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo.*'
        line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
        validate: visudo -cf %s
      become: yes
