---
- hosts: all
  name: Effect ability to listen to Spotify

  vars:
    deps:
      apt:
        - mpc
        - ncmpcpp

  roles:
    - packages

- include: init-sound.yaml
  tags: sound

- include: install-mopidy.yaml
  tags: mopidy

- include: install-abduco.yaml
  tags: abduco
