- name: Initialize paths
  hosts: all

  tasks:
    - name: Initialize path
      file:
        path:
          "{{ item }}"
        state:
          directory
      with_items:
        - "{{ download_path }}"
        - "{{ user_bin }}"
