---
- hosts: all
  name: Install Python development packages

  vars:
    deps:
      apt:
        - libffi-dev
        - libssl-dev
        - libyaml-dev
        - python-dev
        - python3-dev
        - python-pyflakes
        - python3-pyflakes
        - python-virtualenv
        - python3-virtualenv

  roles:
    - packages
