---
- name: Install sudo, add user to sudo/wheel group and allow passwordless sudo
  hosts: all

  vars_files:
    - vars/user_vars.yaml

  vars:
    username: "{{ local_user }}"
    sudo_group: sudo
    sudo_file: /etc/sudoers

    wheel_users:
      - FreeBSD
      - RedHat
      - Archlinux

    deps:
      apt: sudo
      dnf_yum: sudo
      pacman: sudo
      pkg: sudo
      portage: sudo

    _update_cache:
      yes

  roles:
    - packages

  tasks:
    - name: Set sudo group
      set_fact:
        sudo_group: wheel
      when: ansible_os_family in wheel_users
      tags: sudo

    - name: Set sudoers file
      set_fact:
        sudo_file: /usr/local/etc/sudoers
      when: ansible_os_family == "FreeBSD"
      tags: sudo

    - name: Add user {{username}}
      user: name={{username}} group=users groups={{ sudo_group }} shell=/bin/bash
      when: ansible_os_family != "FreeBSD"
      become: yes
      tags: user, group

    - name: Add group {{ username }}
      group: name={{ username }}
      when: ansible_os_family == "FreeBSD"
      become: yes
      tags: group

    - name: Add user {{username}}
      user: name={{ username }} group={{ username }} groups={{ sudo_group }} shell=/bin/sh
      when: ansible_os_family == "FreeBSD"
      become: yes
      tags: user

    - name: Set passwordless sudo for the sudo group
      lineinfile: "dest={{ sudo_file }} state=present regexp='^%{{ sudo_group }}' line='%{{ sudo_group }}   ALL=(ALL:ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
      become: yes
      tags: sudo

- include:
    add-authorized-ssh-key.yaml
