---
- include:
    init-workstation.yaml
  tags:
    workstation

- include:
    install-stumpwm.yaml
  tags:
    stumpwm

- include:
    set-install-backlight
  tags:
    backlight

- hosts: all
  name: Initialize caesium

  vars:
    deps:
      apt:
        - network-manager

  roles:
    - packages
