---
- hosts: all
  vars_files:
    - paths.yaml
  roles:
    - { role: source_install,
        name: dmenu,
        repo: "git://git.suckless.org/dmenu",
        apt: [libfreetype6-dev, libxft-dev, libxinerama-dev],
        dnf: [freetype-devel, libXft-devel, libXinerama-devel],
        portage: [x11-libs/libXinerama],
        clean: true,
        configure: false,
        edit_config: yes,
        config_file: "config.h",
        lines_to_change: [ { "before": "monospace:size=[0-9]+",
                             "after": "monospace:size=11" } ] }
