---
- import_playbook:
    install-youtube-dl.yaml
  vars:
    setuptools:
      virtualenv_name:
        mpsyt

- import_playbook:
    enable-rpm-fusion.yaml

- hosts: all
  name: Install mpyst

  vars:
    deps:
      apt:
        mpv
      dnf_yum:
        mpv
    repo:
      url:
        https://github.com/mps-youtube/mps-youtube.git
    setuptools:
      virtualenv_name:
        mpsyt

  roles:
    - packages
    - setuptools
