---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - project: profanity
    - repo: https://github.com/boothj5/profanity.git
    - apt_packages: [autoconf-archive, pkg-config, libxml2-dev, libtool,
                         libexpat1-dev, libncurses5-dev, libncursesw5-dev,
                         libglib2.0-dev, libcurl4-openssl-dev, libreadline6-dev,
                         uuid-dev, libnotify-dev]
  roles:
    - os_packages
    - git_clone
    - { role: autotools_project, configuration: "--enable-notifications"}
    - ldconfig
