---
- hosts: all
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - ruby
        - git
    - gem: name=homesick state=latest user_install=yes
  tasks:
    - script: add-gems-bin-to-path.sh
