---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - project: dzen
    - repo: https://github.com/robm/dzen.git
    - apt: libxft-dev
  roles:
    - os_packages
    - git_clone
    - autotools_project
