---
- import_playbook:
    install-youtube-dl.yaml
  vars:
    setuptools:
      name:
        mpsyt

- hosts: all
  name: Install mpyst

  vars:
    deps:
      apt:
        mpv
      dnf_yum:
        mpv
    repo:
      url:
        https://github.com/mps-youtube/mps-youtube.git
    setuptools:
      name:
        mpsyt

  pre_tasks:
    - import_tasks:
        enable-rpm-fusion.yaml

  roles:
    - packages
    - setuptools
