---
- hosts: all
  vars_files:
    - paths.yaml
  roles:
    - { roles: source_install,
        clone_source: no,
        name: libstpotify,
        release: "https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz",
        reconf: no,
        configure: no,
        make: no }
