---
- hosts: all
  name: Install several useful things

  vars_files:
    - vars/paths.yaml

  vars:
    deps:
      apt:
        - bind9-host
        - emacs
        - fish
        - htop
        - jq
        - lnav
        - lynx
        - mutt
        - rlwrap
        - screen
        - silversearcher-ag
        - strace
        - surfraw
        - sxiv
        - tig
        - tmux
        - urlview
        - vim
        - vim-gtk
        - w3m
        - whois
        - xsel
        - zathura

      dnf_yum:
        - emacs
        - fish
        - htop
        - jq
        - screen
        - tig
        - tmux
        - vim-enhanced
        - vim-X11
        - w3m
        - xsel

  roles:
    - packages
