---
- include: install-x.yaml
  tags: xorg

- hosts: all
  name: Install StumpWM

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      name: stumpwm
      url: https://github.com/stumpwm/stumpwm

    deps:
      apt: [sbcl, x11-utils, texinfo]
      dnf_yum:
        - sbcl
      portage: dev-lisp/sbcl

  roles:
    - packages
    - clone

  post_tasks:
    - name: Create download path
      file:
        path:
          "{{ download_path }}"
        state:
          directory
      tags: quicklisp

    - name: Download quicklisp
      get_url:
        url: https://beta.quicklisp.org/quicklisp.lisp
        dest: "{{ download_path }}"
      tags: quicklisp

    - name: Install Quicklisp and add it to init file
      command: sbcl --load "{{ download_path }}/quicklisp.lisp" --eval '(quicklisp-quickstart:install)' --eval '(ql:add-to-init-file)'
      args:
        creates: "{{ user_home }}/.sbclrc"
      tags: quicklisp

    - name: Install packages with Quicklisp
      command: sbcl --eval '(ql:quickload "{{ item }}")'
      with_items:
        - clx
        - cl-ppcre
      tags: quicklisp, quicklisp-deps

- include: build-stumpwm.yaml
  tags: build, install

- include: install-stumpwm-utils.yaml
  tags: utils
