---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - repo_path: "{{repo_clone_path}}/stumpwm"
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - git
        - sbcl
        - autoconf
        - x11-utils
        - texinfo
      when: ansible_os_family == "Debian"
    - name: Install requirements with portage
      portage: name=dev-lisp/sbcl state=present
      become: yes
      when: ansible_distribution == "Gentoo"
      tags: install-reqs
  tasks:
    - name: Clone Stumpwm repo
      git: repo=https://github.com/stumpwm/stumpwm dest={{repo_path}}
    - name: Install Stumpwm
      script: install-stumpwm.sh {{repo_path}}
      become: yes
      tags: install
