---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - project: dunst
    - repo: https://github.com/knopwob/dunst.git
    - apt: [libcairo2-dev, libdbus-1-dev, libpango1.0-dev,
                     libxdg-basedir-dev, libxss-dev]
    - dnf_yum: [cairo-devel, dbus-devel, libxdg-basedir-devel,
                         libXScrnSaver-devel, pango-devel]
    - portage: dev-libs/libxdg-basedir
    - configuration_path: "{{user_home}}/.config/dunst"
  roles:
    - os_packages
    - git_clone
    - autotools_project
  tasks:
    - name: Create configuration directory
      file: path={{configuration_path}} state=directory
      tags: config
    - name: Copy sample configuration
      command: cp {{clone_path}}/dunstrc {{configuration_path}}
      tags: config
