---
- hosts: all
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - zenity
        - curl
        - jockey-common
        - libopenal1:i386
        - libxrandr2:i386
        - libssl1.0.0:i386
        - libglu1-mesa:i386
  tasks:
    - script: install-steam.sh