---
- hosts: all
  vars_files:
    - vars/paths.yaml
  vars:
    - project: stumpwm
    - repo: https://github.com/stumpwm/stumpwm
    - apt: [sbcl, x11-utils, texinfo]
    - portage: dev-lisp/sbcl
  roles:
    - os_packages
    - git_clone
    - autotools_project
