---
- hosts: all
  name: Install over-here

  vars:
    deps:
      apt:
        - dbus-x11
        - libdbus-1-dev
    repo:
      name: over-here
      url: https://github.com/femnad/over-here.git
    systemd_service:
      exec: '{{ cargo_bin }}/over-here'
      name: over-here
      description: Simpleton notification daemon

  roles:
    - packages
    - cargo/source-install
    - systemd-service

- import_playbook: cnl-notify-recv.yaml
...
