---
- hosts: all
  name: Install Ansible

  vars_files:
    - vars/paths.yaml

  vars:
    deps:
      apt:
        sshpass
    virtualenv_path:
      "{{ virtualenv_base }}/ans"
    pip_deps:
      ansible:
        2.2.0

  roles:
    - packages
    - pip_packages
