---
- hosts: all
  name: Install HipChat desktop application

  tasks:
    - name: Add HipChat repository
      apt_repository:
        repo:
          deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client {{ ansible_lsb.codename }} main
        state:
          present
        filename:
          atlassian-hipchat4.list
      become:
        yes

    - name: Add HipChat apt key
      apt_key:
        url:
          https://atlassian.artifactoryonline.com/atlassian/api/gpg/key/public
        state:
          present
      become:
        yes

    - name: Install HipChat
      apt:
        name:
          hipchat4
        state:
          latest
        update_cache:
          yes
      become:
        yes
