---
- hosts: all
  vars_files:
    - paths.yaml
  pre_tasks:
    - name: Install requirements with apt
      apt: name={{item}} state=latest
      become: yes
      with_items:
        - python-gst0.10
        - gstreamer0.10-plugins-good
        - gstreamer0.10-plugins-ugly
        - gstreamer0.10-tools
        - dtach
        - python-dev
      when: ansible_os_family == "Debian"
      tags: install-reqs
    - name: Install requirements with dnf
      dnf: name={{item}} state=latest
      become: yes
      with_items:
        - dtach
        - gcc
        - gstreamer-python
        - gstreamer-plugins-good
        - gstreamer-plugins-ugly
        - gstreamer-plugins-bad-free
        - gstreamer-plugins-bad-nonfree
        - libffi-devel
        - python-devel
        - python-pip
      when: ansible_distribution == "Fedora"
      tags: install-reqs
  tasks:
    - name: Install libspotify;
      script: install-libspotify.sh {{release_download_path}}
      tags: install-libs
      become: yes
    - name: Install pip packages
      pip: name={{item}} virtualenv={{common_virtualenv}}
      with_items:
        - mopidy
        - pyspotify
        - Mopidy-Spotify
        - Mopidy-Spotify-Tunigo
      tags: install
