---
- name: Install ncmpcpp
  hosts: all

  vars:
    repo:
      name: ncmpcpp
      url: git://repo.or.cz/ncmpcpp.git
    deps:
      apt: [libcurl4-openssl-dev, libmpdclient-dev, libboost-all-dev,
            libreadline-dev, libncurses5-dev, libncursesw5-dev]
      dnf_yum: [boost, boost-devel, boost-filesystem, boost-locale,
                boost-program-options, boost-regex, boost-thread,
                libcurl-devel, libmpdclient-devel, ncurses-devel,
                readline-devel]

    build:
      configuration: --with-curl

  roles:
    - source_install
