---
- include:
    install-node.yaml
  tags:
    node
  when:
    # Debian (jessie) packages are too old
    ansible_distribution == "Debian"

- hosts: all
  name: Install Zulip Electron client

  vars_files:
    - vars/paths.yaml

  vars:
    deps:
      apt:
        - nodejs
        - nodejs-legacy
        - npm
    repo:
      name: zulip-electron
      url: https://github.com/zulip/zulip-electron.git

  roles:
    # Debian (Jessie) packages are too old
    - { role: packages, when: ansible_distribution != "Debian" }
    - clone

  tasks:
    - name: Install npm dependencies
      command: npm install
      args:
        chdir: "{{ source.path }}"
      tags: install

    - name: Add launcher script
      blockinfile:
        dest:
          "{{ user_bin }}/zulip-electron"
        block: |
          #!/usr/bin/env bash
          cd {{ source.path }}
          npm start
        create:
          yes
        marker:
          ""
        mode:
          0755
      tags: script
    - name: Remove empty lines from the script
      replace:
        dest:
          "{{ user_bin }}/zulip-electron"
        regexp:
          ^$\n
      tags: script
