---
- hosts: all
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes    
      with_items:
        - build-essential
        - ncurses-dev
        - libncurses5-dev
        - gettext
        - git
        - autoconf
        - automake
      when: ansible_os_family == "Debian"
    - dnf: name={{item}} state=latest
      become: yes
      when: ansible_distribution == "Fedora"
      with_items:
        - autoconf
        - automake
        - gcc-c++
        - ncurses-devel
  tasks:
    - git: repo=https://github.com/fish-shell/fish-shell.git dest=~/z/dy/fish-shell
    - script: install-fish.sh
