---
- hosts: all
  vars_files:
    - creds.yaml
    - paths.yaml
  tasks:
    - name: Install requirements with apt
      apt: name={{item}} state=latest
      become: yes
      with_items:
        - gnupg2
        - git
        - pass
      when: ansible_os_family == "Debian"
      tags: reqs
    - name: Install requirements with dnf
      dnf: name={{item}} state=latest
      become: yes
      with_items:
        - gnupg2
        - git
        - pass
      when: ansible_distribution == "Fedora"
      tags: reqs
    - name: Ensure that the export directory exists
      file: path={{gpg_export_dir}} state=directory
      tags: copy
    - name: Copy the GPG private key to remote machine
      copy: src={{gpg_key_location}} dest={{gpg_key_location}}
      tags: copy
    - name: Initialize pass
      script: init-pass.sh {{gpg_key_location}} {{gpg_id}}
      tags: init
