---
- import_playbook:
    install-youtube-dl.yaml
  vars:
    setuptools:
      virtualenv_name:
        mpsyt

- hosts: all
  name: Install mpyst

  vars_files:
    - vars/paths.yaml

  vars:
    deps:
      apt:
        mpv
    repo:
      url:
        https://github.com/mps-youtube/mps-youtube.git
    setuptools:
      virtualenv_name:
        mpsyt

  roles:
    - packages
    - setuptools
