---
- hosts: all
  name: Download and extract Go

  vars:
    go_version: 1.12.4
    download_and_link:
      url: https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
      link:
        - src: bin/go
      purge_dir: go

  roles:
    - download-and-link
...
