---
- hosts: all
  name: Install several useful things

  vars_files:
    - vars/paths.yaml

  vars:
    deps:
      apt:
        - emacs
        - fish
        - htop
        - jq
        - screen
        - silversearcher-ag
        - surfraw
        - tig
        - tmux
        - vim
        - vim-gtk
        - w3m
        - xsel

      dnf_yum:
        - emacs
        - fish
        - htop
        - jq
        - screen
        - tig
        - tmux
        - vim-enhanced
        - vim-X11
        - w3m
        - xsel

  roles:
    - packages

  post_tasks:
    - name: Create vim swap directory
      file:
        path:
          "{{ user_home }}/.vim/swap"
        state:
          directory
