---
- hosts: all

  vars_files:
    - paths.yaml
    - gpg_vars.yaml

  roles:
    - { role: packages, apt: [gnupg2, git, pass] }

  tasks:
    - name: Ensure that the export directory exists
      local_action: file path={{gpg_export_dir}} state=directory
      tags: export
    - name: Export gpg key
      local_action: command gpg --output {{gpg_key_location}} --armor --export-secret-keys {{gpg_id}}
      tags: export
    - name: Ensure that the copy directory exists
      file: path={{gpg_export_dir}} state=directory
      tags: export
    - name: Copy the GPG private key to remote machine
      copy: src={{gpg_key_location}} dest={{gpg_key_location}}
      tags: export
    - name: Initialize pass
      shell: |
        gpg --import {{gpg_key_location}}
        pass init {{gpg_id}}
        git init {{user_home}}/.password-store
      tags: init
    - name: Cleanup local export
      local_action: command shred {{gpg_key_location}}
      tags: cleanup
    - name: Cleanup local directory
      local_action: file path={{gpg_export_dir}} state=absent
      tags: cleanup
    - name: Cleanup remote
      shell: |
        shred {{gpg_key_location}}
        rm -r {{gpg_export_dir}}
      tags: cleanup
