---
- hosts: all
  tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - emacs
        - screen
        - surfraw
        - tmux
        - vim
        - w3m
        - xdotool
      when: ansible_os_family == "Debian"
    - dnf: name={{item}} state=latest
      become: yes
      with_items:
        - emacs
        - screen
        - surfraw
        - tmux
        - vim
        - w3m
        - xdotool
      when: ansible_distribution == "Fedora"
    - git: repo=https://github.com/tpope/vim-pathogen.git dest=/tmp/vim-pathogen
    - file: path=/home/femnad/.vim/autoload state=directory
    - command: cp -r /tmp/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload
