---
- vars_files:
    - paths.yaml
  hosts: all
  pre_tasks:
    - name: Install requirements with apt
      apt: name={{item}} state=latest
      become: yes
      with_items:
        - libmpdclient-dev
        - libboost-all-dev
        - libreadline-dev
        - libncurses5-dev
        - libncursesw5-dev
      when: ansible_os_family == "Debian"
      tags: install-reqs
    - name: Install requirements with dnf
      dnf: name={{item}} state=latest
      become: yes
      with_items:
        - boost
        - boost-devel
        - boost-filesystem
        - boost-locale
        - boost-program-options
        - boost-regex
        - boost-thread
        - libmpdclient-devel
        - ncurses-devel
        - readline-devel
      when:
        - ansible_distribution == "Fedora"
      tags: install-reqs
  tasks:
    - name: Install ncmpcpp
      script: install-ncmpcpp.sh {{release_download_path}}
      tags: install
