---
- name: Install Go stuff
  hosts: all

  vars:
    packages:
      - ratilf
      - stuff

  tasks:
    - name: Go get package
      command: go get github.com/femnad/{{ item }}/...
      loop: '{{ packages }}'
