---
- hosts: all
  vars_files:
    - paths.yaml
  roles:
    - { role: source_install,
        name: dzen,
        repo: "https://github.com/robm/dzen.git",
        apt: libxft-dev,
        configure: false }
