---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - project: dmenu
    - project_repo: git://git.suckless.org/dmenu
  roles:
    - { role: os_packages,
        apt_packages: [libfreetype6-dev, libxft-dev, libxinerama-dev],
        dnf_packages: [freetype-devel, libXft-devel, libXinerama-devel],
        emerge_packages: [x11-libs/libXinerama] }
    - { role: git_clone }
    - { role: autotools_project }
