---
- hosts: all
  name: Install Dunst

  vars:
    repo:
      name: dunst
      url: https://github.com/knopwob/dunst.git
    deps:
      apt:
        - libcairo2-dev
        - libdbus-1-dev
        - libgtk2.0-dev
        - libnotify-dev
        - libpango1.0-dev
        - libxdg-basedir-dev
        - libxss-dev
      dnf_yum:
        - cairo-devel
        - dbus-devel
        - libxdg-basedir-devel
        - libXScrnSaver-devel
        - pango-devel
    build:
      configure: false

  roles:
    - source_install
...
