---
- hosts: all
  name: Install Highlight

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      url:
        https://github.com/andre-simon/highlight.git

    deps:
      apt:
        - libboost-dev
        - liblua5.2-dev
        - lua5.2

    build:
      reconf:
        no
      configure:
        no
      edit_config:
        yes

    util:
      replace:
        - file:
            src/makefile
          before:
            LUA_CFLAGS=.*
          after:
            LUA_CFLAGS=$(shell pkg-config --cflags lua5.2) -DUSE_LUA52
        - file:
            src/makefile
          before:
            LUA_LIBS=.*
          after:
            LUA_LIBS=$(shell pkg-config --libs lua5.2)

  roles:
    - source_install
