---
- name: Install emacs
  hosts: all

  vars:
    deps:
      apt:
        - libgif-dev
        - libgtk-3-dev
        - libgnutls28-dev
        - libtiff5-dev
        - libxpm-dev
    repo:
      url: git://git.sv.gnu.org/emacs.git
      version: emacs-26.1

  roles:
    - packages
    - source_install
