---
- hosts: all

  vars_files:
    - paths.yaml

  roles:
    - { role: source_install,
        name: tin,
        repo: "http://bzr.tin.org/",
        repo_type: bzr,
        reconf: no,
        configuration: "--with-screen=ncursesw",
        apt: [bison, libncursesw5-dev],
        make_command: build }
