---
- hosts: all
  name: Install fish-shell

  vars:

    repo:
      url: https://github.com/fish-shell/fish-shell.git
      version: 3.0.2

    deps:
      apt: [bc, g++, ncurses-dev]
      dnf_yum: [bc, gcc-c++, ncurses-devel]
      pkg: [gnubc]
      portage: [sys-devel/bc]

    build:
      cmake: true

  roles:
    - source_install
...
