---
- hosts: all
  name: Install rossa

  vars:
    deps:
      apt:
        - libnotify-dev
    repo:
      url:
        https://github.com/femnad/rossa.git
    build:
      configure: no
    systemd_service:
        description: Simpleton battery monitor
        name: rossa
        exec: "{{ user_bin }}/rossa"

  roles:
    - source_install
    - systemd-service
...
