---
- name: Download and install libspotify
  hosts: all

  vars_files:
    - vars/paths.yaml

  vars:

    release:
      name: libspotify
      url: https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz

    build:
      reconf: no
      configure: no
      make: no

  roles:
    - release_install

  post_tasks:
    - name: Add local lib to ld cache
      shell: echo '/usr/local/lib' > /etc/ld.so.conf.d/usr-local-lib.conf
      become: yes
      tags: ld-conf

    - name: Run ldconfig
      command: ldconfig
      become: yes
      tags: ld-conf
