---
- hosts: all
  name: Install xchainkeys

  vars_files:
    - vars/paths.yaml

  vars:

    deps:
      apt:
        libx11-dev

    repo:
      name:
        xchainkeys
      url:
        https://github.com/hbekel/xchainkeys.git

  roles:
    - source_install
