---
- hosts: all
  name: Install Dunst

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      name: dunst
      url: https://github.com/knopwob/dunst.git
    deps:
      apt: [libcairo2-dev, libdbus-1-dev, libpango1.0-dev,
            libxdg-basedir-dev, libxss-dev]
      dnf_yum: [cairo-devel, dbus-devel, libxdg-basedir-devel,
                libXScrnSaver-devel, pango-devel]
    build:
      configure: false
    configuration_path: "{{user_home}}/.config/dunst"

  roles:
    - source_install

  tasks:
    - name: Create configuration directory
      file: path={{ configuration_path }} state=directory
      tags: config
    - name: Copy sample configuration
      command: cp {{ source.path }}/dunstrc {{ configuration_path }}
      tags: config
