---
- hosts: all
  name: Install over-here

  vars:
    deps:
      apt:
        - dbus-x11
        - libdbus-1-dev
    repo:
      name: over-here
      url: https://github.com/femnad/over-here.git
    user_service_dir: '{{ ansible_user_dir }}/.config/systemd/user'

  roles:
    - packages
    - cargo/source-install

  post_tasks:
    - name: Ensure user service dir
      file:
        path: '{{ user_service_dir }}'
        state: directory

    - name: Copy the service file
      copy:
        src: '{{ source.path }}/contrib/over-here.service'
        dest: '{{ user_service_dir }}'

    - name: Start and enable the service
      systemd:
        name: over-here
        state: started
        enabled: yes
        user: yes
        daemon-reload: yes

- import_playbook: cnl-notify-recv.yaml
...
