---
- hosts: all
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - libmpdclient-dev
        - libboost1.58-dev
        - libboost-filesystem1.58-dev
        - libboost-locale1.58-dev        
        - libboost-program-options1.58-dev
        - libboost-regex1.58-dev
        - libboost-thread1.58-dev
        - libreadline-dev
        - libncurses5-dev
        - libncursesw5-dev
      when: ansible_os_family == "Debian"
    - dnf: name={{item}} state=latest
      become: yes
      with_items:
        - boost
        - boost-devel
        - boost-filesystem
        - boost-locale
        - boost-program-options
        - boost-regex
        - boost-thread
        - libmpdclient-devel
        - ncurses-devel
        - readline-devel
      when:
        - ansible_distribution == "Fedora"
  tasks:
    - script: install-ncmpcpp.sh
