---
- hosts: all
  name: Install ysnpassmenu

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      name: ysnpassmenu
      url: "https://github.com/femnad/ysnpassmenu.git"
    util:
      link:
        - ysnpassmenu
        - contrib/ysnrofi
    deps:
      apt:
        - rofi

  roles:
    - clone
    - packages
    - util

- import_playbook: install-dmenu.yaml
  tags: dmenu

- import_playbook: install-xdotool.yaml
  tags: xdotool
