---
- hosts: all
  tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - build-essential
        - python-dev
        - python3-dev
        - python-pip
        - python3-pip
        - python-wheel
        - python3-wheel
      when: ansible_os_family == "Debian"
