---
- hosts: all
  name: Install sakura

  vars_files:
    - vars/paths.yaml

  vars:
    deps:
      apt:
        - libglib2.0-dev
        - libgtk-3-dev
        - libvte-2.91-dev
    repo:
      name:
        sakura
      url:
        'lp:sakura'
      type:
        bzr
    build:
      cmake:
        yes

  roles:
    - source_install
