---
- hosts: all
  name: Install fzf

  vars:
    install_script_directory:
      "{{ user_home }}/.fzf"
    install_script:
      "{{ install_script_directory }}/install"

  vars_files:
    - vars/paths.yaml

  tasks:
    - name: Clone fzf for installation
      git:
        repo:
          https://github.com/junegunn/fzf.git
        depth:
          1
        dest:
          "{{ install_script_directory }}"

    - name: Run fzf installation script
      command:
        "{{ install_script }}"
