---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - project: dmenu
    - repo: git://git.suckless.org/dmenu
  roles:
    - { role: os_packages,
        apt: [libfreetype6-dev, libxft-dev, libxinerama-dev],
        dnf: [freetype-devel, libXft-devel, libXinerama-devel],
        portage: [x11-libs/libXinerama] }
    - git_clone
    - { role: autotools_project, clean: true,
        generated_artifacts: ["config.h"] }
