---
- hosts: all
  name: Install ysnpassmenu

  vars:
    deps:
      apt:
        - rofi

  roles:
    - clone
    - packages
    - util

- import_playbook: install-dmenu.yaml
  tags: dmenu

- import_playbook: install-xdotool.yaml
  tags: xdotool
