---
- hosts: all
  name: Install Google Play Music™ Desktop Player

  vars:
    repo:
      url: http://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-.git
    deps:
      apt:
        - libavahi-compat-libdnssd-dev

  roles:
    - clone
    - packages

  post_tasks:
    - name: Install Node.js via snap
      command: snap install node --classic --channel=10
      when: ansible_distribution == 'Ubuntu'
      become: yes

    - name: Install GPM desktop player
      shell: |
        set -e
        npm install
        npm run build
      args:
        chdir: '{{ source.path }}'

    - name: Add launcher script
      lineinfile:
        path: '{{ user_bin }}/google-play-music-desktop-player'
        line: |
          #!/usr/bin/env bash
          pushd {{ source.path }}
          npm start
          popd
        create: yes
        mode: 0755
...
