---
- hosts: all
  name: Install several useful things

  vars:
    deps:
      apt:
        - emacs
        - screen
        - surfraw
        - tmux
        - vim
        - w3m

  roles:
    - packages
