---
- include: install-libspotify.yaml

- name: Install mopidy
  hosts: all

  vars_files:
    - paths.yaml
    - virtualenv_vars.yaml

  vars:

    virtualenv_path: "{{ base_virtualenv_path }}/mopidy"

    deps:
      apt:
        [gcc, gstreamer0.10-plugins-good, gstreamer0.10-plugins-ugly,
         gstreamer0.10-tools, python-dev, python-gst0.10]
      dnf_yum:
        [gstreamer-python, gstreamer-plugins-good, gstreamer-plugins-ugly,
         gstreamer-plugins-bad-free, gstreamer-plugins-bad-nonfree, libffi-devel,
         python-devel, python-pip]
      portage:
        [dev-python/pygobject, media-libs/gstreamer, media-libs/gst-plugins-bad,
         media-libs/gst-plugins-base, media-libs/gst-plugins-good,
         media-libs/gst-plugins-ugly]

    pip_deps:
      Mopidy:
        2.0.1
      pyspotify:
        2.0.5
      Mopidy-Spotify:
        3.0.0
      Mopidy-Spotify-Tunigo:
        1.0.0

  roles:
    - packages
    - pip_packages
