---
- hosts: all
  name: Install Spotify desktop client

  tasks:
    - name: Add apt key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
      become: yes

    - name: Add apt repository
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
        filename: spotify
      become: yes

    - name: Install Spotify client
      apt:
        name: spotify-client
        state: present
        update-cache: yes
      become: yes
