---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - project: stumpwm
    - repo: https://github.com/stumpwm/stumpwm
    - apt_packages: [sbcl, x11-utils, texinfo]
    - portage_packages: dev-lisp/sbcl
  roles:
    - os_packages
    - git_clone
    - autotools_project
