---
- hosts: all
  name: Install Broadcom driver with restricted license

  vars:
    deps:
      apt:
        - bcmwl-kernel-source
      pacman:
        - broadcom-wl-dkms
        - linux-headers

  roles:
    - packages
