---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - project: xdotool
    - repo: https://github.com/jordansissel/xdotool
    - dnf_yum_packagase: [libxkbcommon-devel, libXtst-devel]
  roles:
    - os_packages
    - git_clone
    - autotools_project
