---
- hosts: all
  vars_files:
    - paths.yaml
  roles:
    - { role: source_install,
        name: fish-shell,
        repo: "https://github.com/fish-shell/fish-shell.git",
        apt: [g++, ncurses-dev],
        dnf_yum: [gcc-c++, ncurses-devel] }
