---
- hosts: all
  name: Install wmname

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      url:
        http://git.suckless.org/wmname
    build:
      configure:
        no

  roles:
    - source_install
