---
- hosts: all
  name: Install StumpWM

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      name: stumpwm
      url: https://github.com/stumpwm/stumpwm

    deps:
      apt: [sbcl, x11-utils, texinfo]
      portage: dev-lisp/sbcl

  roles:
    - packages
    - clone

  post_tasks:
    - name: Download quicklisp
      get_url:
        url: https://beta.quicklisp.org/quicklisp.lisp
        dest: "{{ download_path }}"
      tags: quicklisp

    - name: Install Quicklisp and add it to init file
      command: sbcl --load "{{ download_path }}/quicklisp.lisp" --eval '(quicklisp-quickstart:install)' --eval '(ql:add-to-init-file)'
      args:
        creates: "{{ user_home }}/.sbclrc"
      tags: quicklisp

    - name: Install packages with Quicklisp
      command: sbcl --eval '(ql:quickload "{{ item }}")'
      with_items:
        - clx
        - cl-ppcre
      tags: quicklisp

    - name: Build stumpwm
      shell:
        |
          ./autogen.sh
          ./configure
          make
      args:
        chdir:
          "{{ clone_path }}"
      tags: build

    - name: Install stumpwm
      command: make install
      args:
        chdir:
          "{{ clone_path }}"
      become: yes
