---
- hosts: all
  vars_files:
    - paths.yaml
  roles:
    - { role: source_install,
        name: "the_silver_searcher",
        repo: "https://github.com/ggreer/the_silver_searcher.git",
        apt: [liblzma-dev, libpcre3-dev],
        dnf_yum: [pcre-devel, xz-devel] }
