---
- hosts: all
  name: Install dmenu

  vars_files:
    - vars/paths.yaml

  vars:
    deps:
      apt: [libfreetype6-dev, libxft-dev, libxinerama-dev]
      dnf: [freetype-devel, libXft-devel, libXinerama-devel]
      portage: [x11-libs/libXinerama]

    repo:
      name: dmenu
      url: git://git.suckless.org/dmenu

    build:
      clean: true
      configure: false
      edit_config:
        true

    util:
      replace:
        - file:
            config.h
          before:
            "monospace:size=10"
          after:
            "monospace:size=12"

  roles:
    - source_install
    - util
