---
- hosts: all
  tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - emacs
        - vim
        - surfraw
        - xdotool
      when: ansible_os_family == "Debian"
    - dnf: name={{item}} state=latest
      become: yes
      with_items:
        - emacs
        - vim
        - surfraw
        - xdotool
      when: ansible_distribution == "Fedora"
    - git: repo=https://github.com/tpope/vim-pathogen.git dest=/tmp/vim-pathogen
    - command: mkdir -p ~/.vim/autoload
    - command: cp -r /tmp/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload
