---
- include: install-libmesode.yaml
  tags: deps

- hosts: all

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      name: profanity
      url: https://github.com/boothj5/profanity.git
    deps:
      apt: [libcurl4-openssl-dev, libglib2.0-dev, libncursesw5-dev,
            libnotify-dev, libreadline-dev]
    configuration: "--enable-notifications"

  roles:
    - source_install
