---
- hosts: all
  name: Install packages requiring graphical servers

  vars:
    deps:
      common:
        - xdotool
        - xsel
        - zathura
      apt:
        - vim-gtk
      dnf_yum:
        - vim-X11

  roles:
    - packages
...
