---
- hosts: all
  name: Install xdotool

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      name: xdotool
      url: https://github.com/jordansissel/xdotool

    deps:
      apt: [libxkbcommon-dev, libxtst-dev]
      dnf_yum: [libxkbcommon-devel, libXtst-devel]

    build:
      configure: no

  roles:
    - source_install
