---
- hosts: all
  name: Install Google Chrome

  tasks:
    - name: Install Google Chrome deb package
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      become: yes
      when: ansible_os_family == "Debian"
...
