---
- hosts: all
  name: Clone and link lscd

  vars:
    repo:
      name: lscd
      url: https://github.com/hut/lscd.git
    util:
      link: lscd
      link_directory: "{{ user_bin }}"

  roles:
    - clone
    - util

  post_tasks:
    - name: Change shebang line for Debian/Ubuntu
      replace: dest={{ source.path }}/lscd regexp="#!/bin/sh"
           replace="#!/bin/bash"
      when: ansible_os_family == "Debian"
      tags: change-shebang
