---
- hosts: all
  name: Install Go

  vars_files:
    - vars/paths.yaml

  vars:
    go_version:
      1.7.3
    archive_file_url:
      https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
    go_path_suffix:
      z/sc/gocode
    go_path:
      "{{ user_home }}/{{ go_path_suffix }}"

  tasks:
    - name: Locate .profile file
      find: path="{{ user_home }}" patterns=".*profile" hidden=yes file_type=file
      register: profile_file_path
      tags: profile

    - name: Set profile file
      set_fact:
        profile_file:
          "{{ profile_file_path.files[0].path }}"
      tags: profile

    - name: Download and extract Go archive
      unarchive:
        src:
          "{{ archive_file_url }}"
        dest:
          "{{ release_store_path }}"
        remote_src:
          yes
      tags: download

    - name: Set GOROOT
      lineinfile:
        dest:
          "{{ profile_file }}"
        state:
          present
        line:
          export GOROOT=$HOME/{{ release_store_suffix }}/go
        insertbefore:
          ^export PATH.*
      tags: goroot, profile

    - name: Set GOPATH
      lineinfile:
        dest:
          "{{ profile_file }}"
        state:
          present
        line:
          export GOPATH=$HOME/{{ go_path_suffix }}
        insertbefore:
          ^export PATH.*
      tags: profile, gopath

    - name: Add GOROOT/bin to PATH
      replace:
        dest:
          "{{ profile_file }}"
        regexp:
          ^(export PATH=.*)$
        replace:
          \1:$GOROOT/bin
      tags: goroot, path

    - name: Add GOPATH/bin to PATH
      replace:
        dest:
          "{{ profile_file }}"
        regexp:
          ^(export PATH=.*)$
        replace:
          \1:$GOPATH/bin
      tags: gopath, path

    - name: Create GOPATH directory
      file:
        path:
          "{{ go_path }}"
        state:
          directory
      tags: profile, gopath
