---
- hosts: all
  name: Install Slack

  vars:
    version: 3.3.7

  tasks:
    - name: Install Slack .deb package
      apt:
        deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ version }}-amd64.deb
      become: yes
      when: ansible_os_family == 'Debian'
...
