---
- hosts: all
  name: Install sxiv

  vars_files:
    - vars/paths.yaml

  vars:
    deps:
      apt:
        - libexif-dev
        - libimlib2-dev
      dnf_yum:
        - giflib-devel
        - imlib2-devel
        - libexif-devel
        - libXft-devel

    repo:
      url: https://github.com/muennich/sxiv.git
      name: sxiv

    build:
      configure: no

  roles:
    - source_install
