---
- hosts: all
  vars_files:
    - paths.yaml
    - misc.yaml
  vars:
    - project: mutt
    - repo: http://dev.mutt.org/hg/mutt
  roles:
    - { role: os_packages,
        apt: [libncurses5-dev, libncursesw5-dev, libssl-dev,
              libtokyocabinet-dev, libsasl2-dev],
        dnf_yum: [ cyrus-sasl-devel, tokyocabinet-devel] }
    - { role: hg_clone }
    - { role: autotools_project,
        configuration: "--enable-imap --enable-smtp --enable-hcache --enable-sidebar --with-ssl --with-sasl" }
  tasks:
    - name: Generate header caches
      file: path="{{mutt_header_directory}}/{{item}}header" state=directory
      with_items:
        "{{mutt_prefixes}}"
      tags: cache-header
    - name: Generate message caches
      file: path="{{mutt_header_directory}}/{{item}}message" state=directory
      with_items:
        "{{mutt_prefixes}}"
      tags: cache-message
