---
- hosts: all
  name: Install hangups

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      name:
        hangups
      # This guy has some useful customizations, not ready for upstream though
      url:
        https://github.com/femnad/hangups.git
      version:
        add-libnotify-notification
          
  roles:
    - setuptools
