---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - project: the_silver_searcher
    - repo: https://github.com/ggreer/the_silver_searcher.git
  roles:
    - git_clone
    - { role: os_packages, apt: [liblzma-dev, libpcre3-dev] }
    - autotools_project
