---
- hosts: all
  name: Install Alacritty

  vars:
    repo:
      url:
        https://github.com/jwilm/alacritty.git
    deps:
      common:
        [cmake]
      dnf_yum:
        - expat-devel
        - freetype-devel
        - gcc-c++
    cargo:
      crate: alacritty

  roles:
    - packages
    - clone
    - cargo
