- hosts: all

  vars:

    release:
      name: tarsnap
      url: https://www.tarsnap.com/download/tarsnap-autoconf-1.0.39.tgz

    deps:
      apt:
        [gcc, libc6-dev, libssl-dev, zlib1g-dev, e2fslibs-dev]
      dnf_yum:
        [gcc, glibc-devel, openssl-devel, zlib-devel, e2fsprogs-devel]

    build:
      reconf: no

  roles:
    - release_install
