---
- hosts: all
  name: Install kitty

  vars:
    repo:
      url: https://github.com/kovidgoyal/kitty.git
    build:
      configure: no
      make_install: no
    deps:
      debian:
        - fontconfig-devel
        - harfbuzz-dev
      ubuntu:
        - libfontconfig1-dev
        - libharfbuzz-dev
      common:
        - libpng-devel
        - libxkbcommon-devel
        - libXcursor-devel
        - libXinerama-devel
        - libxkbcommon-x11-devel
        - libXi-devel
        - libXrandr-devel
        - mesa-libGL-devel
    local_icons_dir: "{{ user_home }}/.local/share/icons"

  roles:
    - packages
    - source_install

  post_tasks:
    - name: Create a launcher script
      template:
        src: templates/kitty/script.j2
        dest: "{{ user_bin }}/kitty"
        mode: 0755

    - name: Create desktop file
      template:
        src: templates/kitty/desktop.j2
        dest: "{{ user_home }}/.local/share/applications/kitty.desktop"

    - name: Initialise local icons directory
      file:
        path: "{{ local_icons_dir }}"
        state: directory

    - name: Copy the logo file
      copy:
        src: "{{ source.path }}/logo/kitty.png"
        dest: "{{ local_icons_dir }}/kitty.png"
        remote_src: yes
