---
- hosts: all

  vars_files:
    - paths.yaml
    - misc.yaml

  vars:
    repo:
      name: mutt
      url: http://dev.mutt.org/hg/mutt
      type: hg
    deps:
      apt: [libncurses5-dev, libncursesw5-dev, libssl-dev,
                libtokyocabinet-dev, libsasl2-dev]
      dnf_yum: [cyrus-sasl-devel, ncurses-devel, openssl-devel,
                tokyocabinet-devel]
    build:
      configuration: "--enable-imap --enable-smtp --enable-hcache --enable-sidebar --with-ssl --with-sasl"

  roles:
    - source_install

  tasks:
    - name: Generate header and message caches
      file: path="{{mutt_header_directory}}/{{ item[0] }}{{ item[1] }}" state=directory
      with_nested:
        - "{{mutt_prefixes}}"
        - ['header', 'message']
