---
- hosts: all
  vars:
    - key_file_location: /home/femnad/stuff/keyfile
      gpg_id: etmoi
  tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - gnupg2
        - git
        - pass
      when: ansible_os_family == "Debian"
    - dnf: name={{item}} state=latest
      become: yes
      with_items:
        - gnupg2
        - git
        - pass
      when: ansible_distribution == "Fedora"
    - script: init-pass.sh {{key_file_location}} {{gpg_id}}
