---
- hosts: all
  name: Install mpc

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      name: mpc
      url: git://git.musicpd.org/master/mpc.git
    deps:
      dnf_yum:
        - autoconf-archive

  roles:
    - source_install
