---
- hosts: all
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - python-gst0.10
        - gstreamer0.10-plugins-good
        - gstreamer0.10-plugins-ugly
        - gstreamer0.10-tools
        - dtach
        - python-dev
  tasks:
    - script: install-mopidy.sh
