---
- hosts: all
  name: Install server mwe packages

  vars:
    deps:
      common:
        - colordiff
        - fish
        - htop
        - jq
        - lnav
        - lynx
        - multitail
        - pwgen
        - rlwrap
        - screen
        - strace
        - sxiv
        - tig
        - tmux
        - w3m
      apt:
        - bind9-host
        - dnsutils
        - emacs
        - mutt
        - silversearcher-ag
        - surfraw
        - urlview
        - vim
      dnf_yum:
        - emacs
        - the_silver_searcher
        - vim-enhanced

  roles:
    - packages
