---
- hosts: all
  name: Install zeal

  vars:
    deps:
      common:
        - extra-cmake-modules
      apt:
        - libarchive-dev
        - libqt5webkit5-dev
        - libxcb-keysyms1-dev
        - libqt5x11extras5-dev
        - libsqlite3-dev
      dnf_yum:
        - libarchive-devel
        - libsqlite3x-devel
        - qt5-qtbase-devel
        - qt5-qtwebkit-devel
        - qt5-qtx11extras-devel
        - xcb-util-keysyms-devel

    repo:
      url: https://github.com/zealdocs/zeal.git

    build:
      clean: yes
      cmake: yes
      reconf: no
      configure_command: "{{ _configure_command }}"

  pre_tasks:
    - name: Set configure command for Debian based distros
      set_fact:
        _configure_command:
          qmake -qt5
      when:
        ansible_os_family == "Debian"

    - name: Set configure command for Fedora
      set_fact:
        _configure_command:
          qmake-qt5
      when:
        ansible_distribution == "Fedora"

  roles:
    - source_install
