---
- hosts: all
  vars_files:
    - paths.yaml
  vars:
    - project: xchainkeys
    - repo: https://github.com/hbekel/xchainkeys.git
  roles:
    - os_packages
    - git_clone
    - autotools_project
