---
- hosts: all
  name: Install mpc

  vars:
    repo:
      name: mpc
      url: https://github.com/MusicPlayerDaemon/mpc.git
    deps:
      dnf_yum:
        - autoconf-archive

  roles:
    - source_install
