---
- hosts: all
  vars_files:
    - paths.yaml
  roles:
    - { role: source_install,
        clone_source: no,
        name: tarsnap,
        release: "https://www.tarsnap.com/download/tarsnap-autoconf-1.0.37.tgz",
        reconf: no,
        apt: [gcc, libc6-dev, libssl-dev, zlib1g-dev, e2fslibs-dev],
        dnf_yum: [gcc, glibc-devel, openssl-devel, zlib-devel, e2fsprogs-devel] }
