---
- hosts: all
  name: Install rainbowstream

  vars_files:
    - secrets.yaml

  vars:
    deps:
      apt:
        - libjpeg-dev
    repo:
      url:
        https://github.com/DTVD/rainbowstream.git
    setuptools:
      command:
        develop

  roles:
    - packages
    - setuptools

  post_tasks:
    - name:
        Generate consumer.py
      template:
        dest:
          "{{ source.path }}/rainbowstream/consumer.py"
        src:
          consumer.py.j2

    - name:
        Compile image.so
      command:
        cc -fPIC -shared -o {{ user_home }}/.image.so rainbowstream/image.c
      args:
        chdir:
          "{{ source.path }}"
