---
- hosts: all
  name: Install rofi

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      name: rofi
      url: https://github.com/DaveDavenport/rofi.git
    deps:
      apt:
        [libstartup-notification0-dev, libxcb-ewmh-dev, libxcb-icccm4-dev,
        libxcb-randr0-dev, libxcb-util-dev, libxcb-xinerama0-dev,
        libxcb-xkb-dev, libxkbcommon-x11-dev]

  roles:
    - { role: source_install, version: 1.0.1,
        when: "ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('16.04', '<=')" }
