---
- hosts: all
  pre_tasks:
    - apt: name={{ item }} state=latest
      become: yes
      with_items:
        - gcc
        - libc6-dev
        - make
        - libssl-dev
        - zlib1g-dev
        - e2fslibs-dev
  tasks:
    - script: install-tarsnap.sh