---
- hosts: all
  name: Install jq

  vars_files:
    - vars/paths.yaml

  vars:

    deps:
      apt:
        [bison, flex]
      dnf_yum:
        [bison, flex]

    repo:
      name: jq
      url: https://github.com/stedolan/jq.git

  roles:
    - source_install
