---
- hosts: all
  name: Install ratpoison

  vars:
    deps:
      apt:
        - libxrandr-dev
        - texinfo
    repo:
      url:
        https://git.savannah.nongnu.org/git/ratpoison.git

  roles:
    - packages
    - source_install
