---
- hosts: all
  vars:
    - repo_dest: ~/z/gl/fish-shell
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - build-essential
        - ncurses-dev
        - libncurses5-dev
        - gettext
        - git
        - autoconf
        - automake
        - libtool
      when: ansible_os_family == "Debian"
    - dnf: name={{item}} state=latest
      become: yes
      with_items:
        - autoconf
        - automake
        - gcc-c++
        - ncurses-devel
        - libtool
      when: ansible_distribution == "Fedora"
  tasks:
    - git: repo=https://github.com/fish-shell/fish-shell.git dest=~/z/dy/fish-shell
    - script: install-fish.sh
  tasks:
    - name: clone repo
      git: repo=https://github.com/fish-shell/fish-shell.git dest={{repo_dest}}
    - script: install-fish.sh {{repo_dest}}
      become: yes
