---
- hosts: all
  name: Install yq

  vars:
    go_get:
      packages:
        gopkg.in/mikefarah/yq.v2

  roles:
    - go-get

  post_tasks:
    - name: Symlink binary to yq
      file:
        path: '{{ user_bin }}/yq'
        src: '{{ user_bin }}/yq.v2'
        state: link
