---
- hosts: all
  name: Install wireguard

  vars:
    deps:
      apt:
        - libmnl-dev
        - resolvconf
    repo:
      url: https://git.zx2c4.com/WireGuard
    build:
      configure: no
      makefile_path: src

  roles:
    - packages
    - clone
    - autotools
...
