---
- hosts: all
  name: Install Dzen

  vars_files:
    - vars/paths.yaml

  vars:
    repo:
      name: dzen
      url: https://github.com/robm/dzen.git
    deps:
      apt: [libxft-dev, libxpm-dev]
      dnf_yum:
        - libXft-devel
        - libXpm-devel
    build:
      configure: no
      edit_config: yes
    util:
      config_file: config.mk
      comment_out_lines: ["LIBS", "CFLAGS"]
      comment_in_lines: ["LIBS", "CFLAGS = -Wall"]

  roles:
    - source_install
