---
- hosts: all
  name: Install StumpWM

  vars:
    sbclrc:
      "{{ user_home }}/.sbclrc"

  pre_tasks:
    - name: Create download path
      file:
        path:
          "{{ download_path }}"
        state:
          directory
      tags: quicklisp

    - name: Download quicklisp
      get_url:
        url: https://beta.quicklisp.org/quicklisp.lisp
        dest: "{{ download_path }}"
      tags: quicklisp

    - name: Install Quicklisp
      command: sbcl --load "{{ download_path }}/quicklisp.lisp" --eval '(quicklisp-quickstart:install)' --non-interactive
      tags: quicklisp
      args:
        creates:
          "{{ user_home }}/quicklisp"

    - name: Add Quicklisp to SBCL init file
      lineinfile:
        create:
          yes
        path:
          "{{ sbclrc }}"
        line: |
          #-quicklisp
          (let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp"
                                                 (user-homedir-pathname))))
            (when (probe-file quicklisp-init)
              (load quicklisp-init)))

    - name: Install packages with Quicklisp
      command: sbcl --eval '(ql:quickload "{{ item }}")' --non-interactive
      with_items:
        - alexandria
        - clx
        - cl-ppcre
      tags: quicklisp, quicklisp-deps

  roles:
    - install-stumpwm

  post_tasks:
    - name: Add Xsession file
      copy:
        src: stumpwm.desktop
        dest: /usr/share/xsessions/
      become: yes
...
