---
- hosts: all
  name: Install jq

  vars_files:
    - paths.yaml

  vars:

    deps:
      apt:
        bison
      dnf_yum:
        bison

    repo:
      name: jq
      url: https://github.com/stedolan/jq.git

  roles:
    - source_install
