---
- hosts: all
  name: Install several useful things

  vars:
    deps:
      apt:
        - emacs
        - htop
        - screen
        - surfraw
        - tig
        - tmux
        - vim
        - vim-gtk
        - w3m
        - xsel
      dnf_yum:
        - emacs
        - htop
        - screen
        - tig
        - tmux
        - vim-enhanced
        - vim-X11
        - w3m
        - xsel

  roles:
    - packages
