---
- hosts: all
  name: Install pamixer

  vars:
    deps:
      apt:
        - libboost-program-options-dev
        - libpulse-dev
      dnf_yum:
        - pulseaudio-libs-devel
    build:
      configure: no
    repo:
      url: https://github.com/cdemoulins/pamixer.git

  roles:
    - source_install
