---
- name: Download and install libspotify
  hosts: all

  vars_files:
    - paths.yaml

  vars:

    release:
      name: libspotify
      url: https://developer.spotify.com/download/libspotify/libspotify-12.1.51-Linux-x86_64-release.tar.gz

    build:
      reconf: no
      configure: no
      make: no

  roles:
    - release_install
