---
- hosts: all
  vars_files:
    - paths.yaml
  pre_tasks:
    - apt: name={{ item }} state=latest
      become: yes
      with_items:
        - gcc
        - libc6-dev
        - make
        - libssl-dev
        - zlib1g-dev
        - e2fslibs-dev
      when: ansible_os_family == "Debian"
    - dnf: name={{ item }} state=latest
      become: yes
      with_items:
        - gcc
        - glibc-devel
        - make
        - openssl-devel
        - zlib-devel
        - e2fsprogs-devel
      when: ansible_distribution == "Fedora"
  tasks:
    - name: Install tarsnap
      script: install-tarsnap.sh {{release_download_path}}
      become: yes
      tags: install
