---
- hosts: all
  vars_files:
    - paths.yaml
  roles:
    - { role: source_install,
        name: lnav,
        repo: "https://github.com/tstack/lnav.git",
        apt: [libgpm-dev, libncurses5-dev, libncursesw5-dev, libpcre3-dev,
              libreadline-dev, libsqlite3-dev, zlib1g-dev] }
