---
- include:
    init-dev-python.yaml

- hosts: all
  name: Install Ansible

  vars_files:
    - vars/paths.yaml
    - user_vars.yaml

  vars:
    deps:
      apt:
        sshpass
      dnf_yum:
        sshpass
    repo:
      url:
        https://github.com/ansible/ansible.git

  roles:
    - packages
    - setuptools

  post_tasks:
    - name: Add authorized SSH key
      authorized_key:
        user:
          "{{ ansible_user_id }}"
        key:
          "{{ lookup('file', remote_user_ssh_public_key) }}"
      tags: ssh-key
