---
- hosts: all
  name: Install fish-shell

  vars_files:
    - vars/paths.yaml

  vars:

    repo:
      name: fish-shell
      url: https://github.com/fish-shell/fish-shell.git

    deps:
      apt: [bc, g++, ncurses-dev]
      dnf_yum: [bc, gcc-c++, ncurses-devel]
      pkg: [gnubc]
      portage: [sys-devel/bc]

  roles:
    - source_install
