---
- hosts:
    all
  name:
    Set font configuration for user

  vars:
    font_config_dir:
      "{{ user_home }}/.config/fontconfig/conf.d"

  tasks:
    - name:
        Initialize fontconfig directory
      file:
        path:
          "{{ font_config_dir }}"
        state:
          directory

    - name:
        Link desired font configuration files
      file:
        state:
          link
        src:
          "/usr/share/fontconfig/conf.avail/{{ item }}"
        path:
          "{{ font_config_dir }}/{{ item }}"
      with_items:
        - 10-sub-pixel-rgb.conf
        - 10-hinting-full.conf
        - 11-lcdfilter-default.conf
