---
- hosts:
    all
  name:
    Set font configuration for user

  vars:
    font_config_dir:
      "{{ user_home }}/.config/fontconfig/conf.d"

  tasks:
    - name:
        Initialize fontconfig directory
      file:
        path:
          "{{ font_config_dir }}"
        state:
          directory

    - name:
        Link desired font configuration files
      file:
        src:
          "{{ item }}"
        path:
          "{{ font_config_dir }}"
      with_items:
        - /etc/fonts/conf.avail/10-sub-pixel-rgb.conf
        - /etc/fonts/conf.avail/10-hinting-full.conf
