---
- hosts: all
  name: Set DNS servers for resolved


  tasks:
    - name: Set DNS servers if line is commented
      replace:
        path: /etc/systemd/resolved.conf
        regexp: '#DNS=.*'
        replace: DNS=8.8.8.8 8.8.4.4
      become: yes
...
