---
- hosts: all
  name: Set DNS server for DHCP client

  tasks:
    - name: Set domain name server superseding
      lineinfile:
        path: /etc/dhcp/dhclient.conf
        line: supersede domain-name-servers 8.8.8.8, 8.8.4.4;
      become: yes
...
