---
- name: "Install requirements with apt (initiator: {{ initiator }})"
  apt: name={{item}} state=latest update_cache={{update_cache}}
  with_items:
    "{{ apt }}"
  when: ansible_os_family == "Debian"
  become: yes
  tags: reqs, reqs-apt
- name: "Install requirements with dnf (initiator: {{ initiator }})"
  dnf: name={{item}} state=latest
  with_items:
    "{{ dnf_yum }}"
  when: ansible_distribution == "Fedora"
  become: yes
  tags: reqs, reqs-dnf
- name: "Install packages with pkg (initiator: {{ initiator }})"
  pkgng: name={{ item }} state=present
  with_items:
    "{{ pkg }}"
  when: ansible_distribution == "FreeBSD"
  become: yes
  tags: reqs, reqs-pkg
- name: "Install packages with portage (initiator: {{ initiator }})"
  portage: name={{item}} state=present
  with_items:
    "{{ portage }}"
  when: ansible_distribution == "Gentoo"
  become: yes
  tags: reqs, reqs-portage
- name: "Install packages with yum (initiator: {{ initiator }})"
  yum: name={{item}} state=latest
  with_items:
    "{{ dnf_yum }}"
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
  become: yes
  tags: reqs, reqs-yum
