---
dependencies:
  - { role: git_clone, _repo: "{{repo}}", _name: "{{name}}" }
  - { role: os_packages, _name: "{{name}}",
      _apt: "{{apt}}", _dnf_yum: "{{dnf_yum}}" }
  - { role: autotools_project, _name: "{{name}}",
      source_path: "{{repo_clone_path}}" }
