---
- name: Generate {{ name }} build configuration
  command: autoreconf -i
  args:
    chdir: "{{ source_path }}"
  when: _build.reconf and _build.configure
  tags: build, autoconf
- name: Configure {{ name }}
  command: ./configure {{ _build.configuration }}
  args:
    chdir: "{{ source_path }}"
  when: _build.configure
  tags: build, configure
- name: Set make executable
  set_fact:
    _make_executable:
      gmake
  when:
    ansible_distribution == "FreeBSD"
  tags: build, make, install
- name: Clean {{ name }} artifacts
  command: "{{ _make_executable }} clean"
  args:
    chdir: "{{ source_path}}"
  when: _build.make and _build.clean
  tags: build, clean
- name: Remove generated artifacts
  file: path="{{ source_path }}/{{ item }}" state=absent
  with_items:
    "{{ _build.generated_artifacts }}"
  tags: build, clean
- name: Build {{ name }}
  command: "{{ _make_executable }} {{ _build.make_command }}"
  args:
    chdir: "{{ source_path }}"
  when: _build.make
  tags: build, make
- name: Install {{ name }}
  command: "{{ _make_executable }} install"
  args:
    chdir: "{{ source_path }}"
  when: _build.make or _build.make_install
  become: yes
  tags: install
