---
- name: Init {{ name }} build configuration
  command: autoreconf -i
  args:
    chdir: "{{ source_path }}"
  when: reconf and configure
  tags: build, autoconf
- name: Configure {{ name }}
  command: ./configure {{ configuration }}
  args:
    chdir: "{{ source_path }}"
  when: configure
  tags: build, configure
- name: Set make executable
  set_fact:
    make_executable:
      gmake
  when:
    ansible_distribution == "FreeBSD"
  tags: build, make, install
- name: Clean {{ name }} artifacts
  command: "{{ make_executable }} clean"
  args:
    chdir: "{{ source_path}}"
  when: make and clean
  tags: build, clean
- name: Remove generated artifacts
  file: path="{{ source_path }}/{{ item }}" state=absent
  with_items:
    "{{ generated_artifacts }}"
  tags: build, clean
- name: Build {{ name }}
  command: "{{ make_executable }} {{ make_command }}"
  args:
    chdir: "{{ source_path }}"
  when: make
  tags: build, make
- name: Install {{ name }}
  command: "{{ make_executable }} install"
  args:
    chdir: "{{ source_path }}"
  when: make or make_install
  become: yes
  tags: install
