---
- name: Generate build configuration {{ source.name }}
  command: autoreconf -i
  args:
    chdir: "{{ source.path }}"
  when: _build.reconf and _build.configure
  tags: build, autoconf
- name: Configure {{ source.name }}
  command: ./configure {{ _build.configuration }}
  args:
    chdir: "{{ source.path }}"
  when: _build.configure
  tags: build, configure
- name: Set make executable {{ source.name }}
  set_fact:
    _make_executable:
      gmake
  when:
    ansible_distribution == "FreeBSD"
  tags: build, make, install
- name: Clean artifacts {{ source.name }}
  command: "{{ _make_executable }} clean"
  args:
    chdir: "{{ source.path}}"
  when: _build.make and _build.clean
  tags: build, clean
- name: Remove generated artifacts {{ source.name }}
  file: path="{{ source.path }}/{{ item }}" state=absent
  with_items:
    "{{ _build.generated_artifacts }}"
  tags: build, clean
- name: Build {{ source.name }}
  command: "{{ _make_executable }} {{ _build.make_command }}"
  args:
    chdir: "{{ source.path }}"
  when: _build.make
  tags: build, make
- name: Install {{ source.name }}
  command: "{{ _make_executable }} install"
  args:
    chdir: "{{ source.path }}"
  when: _build.make or _build.make_install
  become: yes
  tags: install
