---
_build_deps:
  apt:
    [autoconf, automake, libtool, make, pkg-config]
  dnf_yum:
    [autoconf, automake, libtool, make, pkgconfig]
  pkg:
    [autoconf, automake, libtool, gmake, pkgconf]
  portage:
    []

_build: "{{ _build_defaults | combine(build) }}"
