---
- name: Clone {{ name }} with git
  git: repo={{ url }} dest={{ clone_path }} accept_hostkey={{ accept_hostkey }}
       force={{ force_discard }} version={{version | default(omit)}}
  when: repo_type == "git"
  tags: clone
- name: Clone {{ name }} with Mercurial
  hg: repo={{ url }} dest={{ clone_path }}
  when: repo_type == "hg"
  tags: clone
- name: Clone {{ name }} with Bazaar
  bzr: name={{ url }} dest={{ clone_path }}
  when: repo_type == "bzr"
  tags: clone
- name: Set release path
  set_fact:
    release_path:
      "{{ clone_path }}"
  tags: clone, build, install, make
