---
- name: Init {{_name}} build configuration
  command: autoreconf -i
  args:
    chdir: "{{source_path}}"
  when: configure
  tags: build, autoconf
- name: Configure {{_name}}
  command: ./configure {{configuration | default("")}}
  args:
    chdir: "{{source_path}}"
  when: configure
  tags: build, configure
- name: Clean {{_name}} artifacts
  command: make clean
  when: clean
  args:
    chdir: "{{source_path}}"
  tags: build, clean
- name: Comment out lines in {{config_file}} for {{_name}}
  replace: dest="{{source_path}}/{{config_file}}" regexp="^({{item}}.*)"
           replace='#\1'
  with_items:
    "{{comment_out_lines}}"
  tags: build, config-edit
- name: Comment in lines in {{config_file}} for {{_name}}
  lineinfile: dest="{{source_path}}/{{config_file}}" regexp="^#({{item}}.*)"
              state=present line='\1' backrefs=yes
  with_items:
    "{{comment_in_lines}}"
  tags: build, config-edit
- name: Remove generated artifacts
  file: path="{{source_path}}/{{item}}" state=absent
  with_items:
    "{{generated_artifacts}}"
  tags: build, clean
- name: Build {{_name}}
  command: make
  args:
    chdir: "{{source_path}}"
  tags: build, make
- name: Install {{_name}}
  command: make install
  args:
    chdir: "{{source_path}}"
  become: yes
  tags: install
