---
- name: Init {{_name}} build configuration
  command: autoreconf -i
  args:
    chdir: "{{source_path}}"
  when: configure
  tags: build, autoconf
- name: Configure {{_name}}
  command: ./configure {{configuration | default(omit)}}
  args:
    chdir: "{{source_path}}"
  when: configure
  tags: build, configure
- name: Clean {{_name}} artifacts
  command: make clean
  when: clean
  args:
    chdir: "{{source_path}}"
  tags: build
- name: Remove generated artifacts
  file: path="{{source_path}}/{{item}}" state=absent
  with_items:
    "{{generated_artifacts}}"
  tags: build
- name: Build {{_name}}
  command: make
  args:
    chdir: "{{source_path}}"
  tags: build, make
- name: Install {{_name}}
  command: make install
  args:
    chdir: "{{source_path}}"
  become: yes
  tags: install
