---
- name: Init {{_name}} build configuration
  command: autoreconf -i
  args:
    chdir: "{{source_path}}"
  when: configure
  tags: build, autoconf
- name: Configure {{_name}}
  command: ./configure {{configuration | default("")}}
  args:
    chdir: "{{source_path}}"
  when: configure
  tags: build, configure
- name: Clean {{_name}} artifacts
  command: make clean
  args:
    chdir: "{{source_path}}"
  when: make and clean
  tags: build, clean
- name: Comment out lines in config file for {{_name}}
  replace: dest="{{source_path}}/{{config_file}}" regexp="^({{item}}.*)"
           replace='#\1'
  with_items:
    "{{comment_out_lines}}"
  when:
    config_file != ""
  tags: build, config-edit
- name: Comment in lines in config file for {{_name}}
  lineinfile: dest="{{source_path}}/{{config_file}}" regexp="^#({{item}}.*)"
              state=present line='\1' backrefs=yes
  with_items:
    "{{comment_in_lines}}"
  when: config_file != ""
  tags: build, config-edit
- name: Remove generated artifacts
  file: path="{{source_path}}/{{item}}" state=absent
  with_items:
    "{{generated_artifacts}}"
  tags: build, clean
- name: Build {{_name}}
  command: make
  args:
    chdir: "{{source_path}}"
  when: make
  tags: build, make
- name: Install {{_name}}
  command: make install
  args:
    chdir: "{{source_path}}"
  when: make
  become: yes
  tags: install
- name: Link {{_name}} executable
  file: src="{{ source_path }}/{{ _name }}"
        dest="{{ link_directory }}/{{ _name }}" state=link
  when: link_directory != ""
  tags: link-file
