---
- name: Init {{project}} build configuration
  command: autoreconf -i
  args:
    chdir: "{{clone_path}}"
    removes: configure.ac
  tags: build, autoconf
- name: Configure {{project}}
  command: ./configure {{configuration | default()}}
  args:
    chdir: "{{clone_path}}"
    removes: configure
  tags: build, configure
- name: Clean {{project}} artifacts
  command: make clean
  when: clean
  args:
    chdir: "{{clone_path}}"
  tags: build
- name: Remove generated artifacts
  file: path="{{clone_path}}/{{item}}" state=absent
  with_items:
    "{{generated_artifacts}}"
  tags: build
- name: Build {{project}}
  command: make
  args:
    chdir: "{{clone_path}}"
    removes: Makefile
  tags: build, make
- name: Install {{project}}
  command: make install
  args:
    chdir: "{{clone_path}}"
    removes: Makefile
  become: yes
  tags: install
